### ISSUE TITLE
[1.19.2] Gui inoperable

### ISSUE THREAD

**Issue by Baggytrousers27** [dragon-forge/ImprovableSkills#1]
Forge 43.1.47
HammerLib-1.19.2-19.1.33
ImprovableSkills-1.19.2-19.1.1

Can't click book in inventory and hammerlib hotkey (hammerlib.render_item) does nothing.

If this was just a non-functional release, please ignore this (can't figure my way around discord just yet).

**Comment by Zeitheron** [comment]
The book in the inventory is inaccessible until you make an actual book.

**Comment by Zeitheron** [comment]
As for the render item hotkey, you must hover over an item in GUI and press it, then it renders the item into a PNG file, right out of your inventory,

**Comment by Baggytrousers27** [comment]
Thank you and sorry for all this.
