### ISSUE TITLE
[1.19.2] Crashes

### ISSUE THREAD

**Issue by Kazutho** [dragon-forge/ImprovableSkills#11]
i was playing for a while with jobs+ mod without problem but after adding improvable skills to my world, whenever i use the vein miner hability from jobs+, improvable skills causes a crash.
[crash-2023-04-10_23.10.24-client.txt](https://github.com/dragon-forge/ImprovableSkills/files/11202481/crash-2023-04-10_23.10.24-client.txt)

**Comment by Zeitheron** [comment]
Should be fixed in 1.20
Will downcast this fix to 1.19.2 on the next build.
