### ISSUE TITLE
[1.20] Inventory bug

### ISSUE THREAD

**Issue by krjencik** [dragon-forge/ImprovableSkills#12]
when i add this mod to mc1.20 inv gets bugged

+ when using survival inventory i dont see blocks im crafting with
+ i really like this mod so im looking forward to when it will be ok again :)

**Comment by krjencik** [comment]
![2023-06-10_13 18 05](https://github.com/dragon-forge/ImprovableSkills/assets/92643141/bbed9abf-02ef-498c-975f-3a6f146be232)

**Comment by Zeitheron** [comment]
Thank you for reporting, I will push a fix build asap.
