### ISSUE TITLE
furnace doesnt show its working

### ISSUE THREAD

**Issue by krjencik** [dragon-forge/ImprovableSkills#13]
when the skill accelerated furnace is on, furnace emits particles, but there is no fire in it.

mc 1.20.1

![2023-06-18_14 59 49](https://github.com/dragon-forge/ImprovableSkills/assets/92643141/9a8e8a3b-fcdf-45ba-986b-410e5519e58d)

**Comment by Zeitheron** [comment]
This is intended behavior and is used to show which furnaces are affected.

**Comment by Takiaaa** [comment]
> 这是预期行为，用于显示哪些炉子受到影响。
粒子存在是用来显示哪些炉子受到影响，但同时熔炉的燃烧状态会消失，也就是说熔炉被影响之后燃烧只会产生粒子而不会有燃烧动画。
