### ISSUE TITLE
Huckster and Soul Speed skills not dropping

### ISSUE THREAD

**Issue by Pentinic** [dragon-forge/ImprovableSkills#15]
Both the librarian gift and piglin trading loot tables both seem to not include their respective skills. I have attempted to find both and after thousands of drops with apparent drop rates of around 33% they have not been dropped.

**Comment by AENykorak** [comment]
Minecraft 1.20.1
ImprovableSkills 20.1.6

I have also noticed no drop rate on the Soul Speed skill.
In addition, was not able to /give the skill page to players on the server.
This suggests the skill page is turned off somehow?
Verified it was active in the config, so perhaps somewhere in the actual code.

**Comment by factorers1** [comment]
Anyone find a fix for this? Honestly its frustrating bc huckster is the only skill I have left to collect

**Comment by mycroftjr** [comment]
I think this may effect 1.19.2 as well?
