### ISSUE TITLE
Source code for the 1.12.2 version of the mod ?

### ISSUE THREAD

**Issue by Shykaruu** [dragon-forge/ImprovableSkills#21]
Hello, Can you add the source code for the 1.12.2 version of the mod please ?

**Comment by Zeitheron** [comment]
1.12.2 is unsupported. Update to later versions.

**Comment by Shykaruu** [comment]
https://www.curseforge.com/minecraft/mc-mods/improvable-skills/files/3930794 ?

**Comment by Shykaruu** [comment]
I want to make modification on the 1.12.2 version of the mod but i can't because of there's no source code of the mod

**Comment by Zeitheron** [comment]
You are not really allowed to modify the mod's code. You are free to develop an addon to add on to the existing mod.

**Comment by Xplodin** [comment]
I think the person wants to make an addon for 1.12.2 but the source code doesnt exist for 1.12.2 anymore on the github.

**Comment by Zeitheron** [comment]
You don't need source code to develop an addon. IntelliJ has a built-in decompiler.

To add the mod to the workspace you'd just have to add it into runtime using `deobfCompile "org.zeith.ImprovableSkills:ImprovableSkills-1.12.2:12.4.68:deobf"` while using `stable_39` mappings.
