### ISSUE TITLE
[MC1.20.1] Crush on disabling abilities

### ISSUE THREAD

**Issue by DarkOutX** [dragon-forge/ImprovableSkills#23]
Game crushes when trying to create new world (or load server) with disabled abilities

MC Version: 1.20.1
Mod Version: 20.1.6
Config (part which makes crush):
```
/* What abilities should be enabled? */
C "Abilities"={
	/* Should Ability "ability.improvableskills:anvil" be added to the game? */
	B "improvableskills:anvil"=false
	
	/* Should Ability "ability.improvableskills:auto_xp_bank" be added to the game? */
	B "improvableskills:auto_xp_bank"=false
	
	/* Should Ability "ability.improvableskills:cowboy" be added to the game? */
	B "improvableskills:cowboy"=false
	
	/* Should Ability "ability.improvableskills:crafter" be added to the game? */
	B "improvableskills:crafter"=false
	
	/* Should Ability "ability.improvableskills:enchanting" be added to the game? */
	B "improvableskills:enchanting"=false
	
	/* Should Ability "ability.improvableskills:magnetism" be added to the game? */
	B "improvableskills:magnetism"=false
}

```
[crash-2024-02-12_16.00.53-client.txt](https://github.com/dragon-forge/ImprovableSkills/files/14238074/crash-2024-02-12_16.00.53-client.txt)

**Comment by CapToad** [comment]
crash* try to remove embeddium and oculus

**Comment by Zeitheron** [comment]
Enable abilities back. That should fix it.
I'll be working on a fix to that.

**Comment by drkanbs** [comment]
I had the same problem, fyi. Just found it today.  I had quite a few disabled, as they make sense for the pack I'm making.  Turned them back on, as you said, and it's working again.
