### ISSUE TITLE
[MC 1.19.2] "Tampered" message in chat displaying for curseforge/modrinth-downloaded mod

### ISSUE THREAD

**Issue by Braebro9k** [dragon-forge/ImprovableSkills#24]
I was making a modpack to play with some friends on curseforge, and I got this warning in the chat.

![image](https://github.com/dragon-forge/ImprovableSkills/assets/154292500/4ebb78a2-ff06-40e2-96da-d91c1d11f531)

I deleted the curseforge version of the mod and installed the version from modrinth, but the same message displayed. Both mod versions were 19.2.12 (the one from 1/20/2024). I can post a full modlist if it's likely to be an incompatibility of some kind.

**Comment by Braebro9k** [comment]
Great mod btw :)

**Comment by Braebro9k** [comment]
Update: The same message appears when creating a world with only Improvable Skills 3 (and HammerLib ig lol) installed, so it doesn't seem to be a mod interaction.

**Comment by jpcrowe** [comment]
Confirming for 19.2.12
