### ISSUE TITLE
Crash when opening book of skills

### ISSUE THREAD

**Issue by NinjaExperto** [dragon-forge/ImprovableSkills#25]
I copy and pasted the crash report into chat gtp and it says this:
The game crashed unexpectedly due to an InjectionError. The error occurred in a mixin injection (org.spongepowered.asm.mixin.injection.throwables.InjectionError). The error occurred in the method GuiGraphics::m_280497_ which is part of the mixin ScreenMixin defined in the mixin configuration file forbidden_arcanus.mixins.json. The error indicates that there are incompatible changes in the Local Variable Table (LVT) at opcode 345. Specifically, the callback forbiddenArcanus_renderTooltipInternal expects an array of RenderTooltipEvent$Pre, but it found an array of Object. I think the error is because the mods "Improvable Skills" and "Forbidden & Arcanus" not working together, not sure exactly why. I hope you can help thanks.

**Comment by Zeitheron** [comment]
forbidden_arcanus
