### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by serhiipetrychenko12319** [dragon-forge/ImprovableSkills#28]
Hi! I made a Russian localization for the mod on version 1.20.1. It would be great if the translation could be available to everyone.
I had to convert the translation from a .lang file to a .txt file to attach it.
[ru_ru.txt](https://github.com/dragon-forge/ImprovableSkills/files/15442316/ru_ru.txt)

**Comment by Zeitheron** [comment]
Please submit a PR, do not create issues for localisations.
