### ISSUE TITLE
1.21 Neoforge Crash

### ISSUE THREAD

**Issue by MokahTGS** [dragon-forge/ImprovableSkills#30]
Getting a client crash: https://gist.github.com/Zeitheron/c0557496dc7007aa5bc0be09c43c5bbc

**Comment by Zeitheron** [comment]
For the time being, downgrade Neoforge, they renamed the event to be a different name. Will release an update for it soon.

**Comment by Zeitheron** [comment]
Patch released 21.0.1 on [Modrinth](https://modrinth.com/mod/improvable-skills/version/21.0.1). CurseForge will follow up soon.
