### ISSUE TITLE
Crash when opening creative Tab

### ISSUE THREAD

**Issue by PinkLasagna03** [dragon-forge/ImprovableSkills#32]
[latest.log](https://github.com/user-attachments/files/16046381/latest.log)
[crash-2024-07-01_00.09.20-client.txt](https://github.com/user-attachments/files/16046383/crash-2024-07-01_00.09.20-client.txt)

What the title said. I also noticed the Skills are not showing up in JEI. Can you maybe help me finding the issue?

**Comment by PanMarudaJakub** [comment]
Same for me
[crash-2024-07-01_00.52.13-client.txt](https://github.com/user-attachments/files/16046466/crash-2024-07-01_00.52.13-client.txt)

**Comment by LioxAcc** [comment]
I was able to solve the problem by downgrading the HammerLib version. (to 20.1.29)
with HammerLib 20.1.30:
![2024-06-23_16 08 44](https://github.com/dragon-forge/ImprovableSkills/assets/170838818/0aad008f-132c-4dc2-a163-abbc94291dd1)

and with HammerLib 20.1.29:
![2024-06-23_16 22 43](https://github.com/dragon-forge/ImprovableSkills/assets/170838818/8eb8bbd4-0999-42c7-a40b-9957e2d00db1)

**Comment by PinkLasagna03** [comment]
> I was able to solve the problem by downgrading the HammerLib version. (to 20.1.29) with HammerLib 20.1.30: ![2024-06-23_16 08 44](https://private-user-images.githubusercontent.com/170838818/345927118-0aad008f-132c-4dc2-a163-abbc94291dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjM4NjAsIm5iZiI6MTcyMDEyMzU2MCwicGF0aCI6Ii8xNzA4Mzg4MTgvMzQ1OTI3MTE4LTBhYWQwMDhmLTEzMmMtNGRjMi1hMTYzLWFiYmM5NDI5MWRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMDA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGQ3Mjc2NTFjOTNkNzYyYmFmY2QyNzlhYmRiYjRiNTFmNmYzZTMzNWM1NmMwZTdiZjQwYjdjNzhjNGRjYmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RFYx1Bs6JV8kFW50dt5VLPhqSZrqdvzK_yHDB8SPLNA)
> 
> and with HammerLib 20.1.29: ![2024-06-23_16 22 43](https://private-user-images.githubusercontent.com/170838818/345927183-8eb8bbd4-0999-42c7-a40b-9957e2d00db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjM4NjAsIm5iZiI6MTcyMDEyMzU2MCwicGF0aCI6Ii8xNzA4Mzg4MTgvMzQ1OTI3MTgzLThlYjhiYmQ0LTA5OTktNDJjNy1hNDBiLTk5NTdlMmQwMGRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMDA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmMxY2Q3Y2FhY2YxYTUwYmE3ZmMyOWZjYjU4MjgzNTE1MDRiZGVmYjY5MzA1NmE4NTg2MWI2MDFkNjQyZDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5qRBU_1X34nhFUoSFg52h6lFNZZK7eNyhbGwv9_mQ_A)

This did the trick, thanks!!

**Comment by Zeitheron** [comment]
1.20.1 - fixed.
