### ISSUE TITLE
UI not opening

### ISSUE THREAD

**Issue by goobermaster** [dragon-forge/ImprovableSkills#35]
whenever i right click i hear the sound of a page turning but no UI shows up idk what i'm doing wrong.

**Comment by Zeitheron** [comment]
Please provide more info.

**Comment by goobermaster** [comment]
the book is working now that i've reopened the world but originally whenever i would right click while holding the book the ui for upgrading skills wouldn't pop up. also when i made the book there was no message in the chat. however i could still hear the sound of the book opening whenever i right clicked.
