### ISSUE TITLE
[Forge 1.20.1] Respawn button stucks when we die

### ISSUE THREAD

**Issue by ikatkat** [dragon-forge/ImprovableSkills#36]
Respawn stuck after of death in single player or online, even if we respawn, the character is red and remains on the ground, even if we can move, we cannot break or pick up anything, it only gets fixed when we leave the server and enter.

**Comment by Zeitheron** [comment]
#4, still no fixes on horizon.

**Comment by ikatkat** [comment]
We love your mod and we are waiting for it to be fixed.
