### ISSUE TITLE
Server crash 1.20.1

### ISSUE THREAD

**Issue by SeagalKru** [dragon-forge/ImprovableSkills#42]
After updating the mod "HammerLib-1.20.1-20.1.35" the server does not start.
The corresponding log files are attached:
[crash-2024-12-24_23.53.47-fml.txt](https://github.com/user-attachments/files/18241914/crash-2024-12-24_23.53.47-fml.txt)
[latest.log](https://github.com/user-attachments/files/18241917/latest.log)

**Comment by Zeitheron** [comment]
Fixed.
