### ISSUE TITLE
Improvable Skills is hiding the icon of the mod "Curios Forge" in the inventory

### ISSUE THREAD

**Issue by SubSonicEr** [dragon-forge/ImprovableSkills#6]
Hey there,

since I've installed the mod "Improvable Skills" for MC 1.19.3 Forge the icon for "Curios Forge" in the inventory to open the extra equipment slots is hidden. I can still open the equipment slot when clicking on the position where the icon should be. Is there is possibility to configure a compability with Curios Forge?

Greetings and a happy new year

**Comment by SubSonicEr** [comment]
Additionally, when the equipment slots of Curios Forge are opened, the icon of improvable skills is hidden in the inventory

**Comment by Zeitheron** [comment]
I do not know of any cause or resolution to this issnoe.
