### ISSUE TITLE
Suggestion/Enhancement: Make abilities configurable too

### ISSUE THREAD

**Issue by lynnpye** [dragon-forge/ImprovableSkills#8]
I'm using both Apotheosis and Improvable Skills. Since Apotheosis heavily modifies the way the Enchanting table works, I would like to make that ability unavailable.

**Comment by lynnpye** [comment]
FWIW, as a workaround, I am able to create a data pack to effectively null out the recipe:

data/improvableskills/recipes/improvableskills/enchanting.json

with content of '{}'

**Comment by Zeitheron** [comment]
Since 1.20 you can disable individual abilities, similarly to how you can disable skills.
