### ISSUE TITLE
Suggestion/Enhancement: add config option to disable parchment fragment loot drops

### ISSUE THREAD

**Issue by lynnpye** [dragon-forge/ImprovableSkills#9]
These can be crafted and there are only 5 total abilities which can be gained using them. Once you have learned all available abilities there is no further use for them, so having them included as a possible drop in every chest seems excessive.

**Comment by Zeitheron** [comment]
Mods may add extra abilities, plus if you don't need the fragments, there is a recipe to convert it into paper.
